language: go

services:
  - docker

go:
  - 1.12.x

env:
  - GO111MODULE=on

jobs:
  include:
    - stage: build
      script:
        - go build
        - ls
    - stage: deploy
      script:
        - go build
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
        - docker build -t mrblnetwork/leaderboards .
        - "docker push mrblnetwork/leaderboards"
        - "docker tag mrblnetwork/leaderboards mrblnetwork/leaderboards:$TRAVIS_TAG"
        - "docker push mrblnetwork/leaderboards:$TRAVIS_TAG"
